apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"api-svc","namespace":"hive"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"internal-api","color":"blue"}}}
  creationTimestamp: "2025-06-20T11:13:17Z"
  name: api-svc
  namespace: hive
  resourceVersion: "576"
  uid: 6a0e4189-d911-4857-b1d0-2f30fd6b599d
spec:
  clusterIP: 10.108.148.111
  clusterIPs:
  - 10.108.148.111
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: internal-api
    color: green #blue
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
