apiVersion: v1
kind: Service
metadata:
  name: hive-io-frontend-svc
  namespace: hive
spec:
  type: ClusterIP
  selector:
    app: hive-io-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80