apiVersion: v1
kind: Pod
metadata:
  name: svc-watch
  namespace: auth
spec:
  serviceAccountName: svc-monitor # auth-sa
  containers:
  - name: busybox
    image: radial/busyboxplus:curl
    command: ['sh', '-c', 'TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token); while true; do if curl -s -o /dev/null -k -m 3 -H "Authorization: Bearer $TOKEN" https://kubernetes.default.svc.cluster.local/api/v1/namespaces/auth/services/; then echo "[SUCCESS] Successfully viewed Services!"; else echo "[FAIL] Failed to view Services!"; fi; sleep 5; done']
