services:
  app:
    image: leticiavalladares/test:latest
    ports:
      - "8080:8080"
    environment:
      - ENV=staging
    profiles:
      - staging

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'