apiVersion: apps/v1
kind: Deployment
metadata:
   name: api-deploy
   labels:
      app: api
spec:
   replicas: 3
   selector:
      matchLabels:
        app: api
   template:
      metadata:
        labels:
            app: api
      spec:
        containers:
        - name: nginx
          image: nginx:1.27.5
          command: ["/bin/sh", "-c", "set -e; while true; do date >> date.txt; sleep 5; done"]
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
