apiVersion: apps/v1
kind: Deployment
metadata:
  name: bees
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bees
  template:
    metadata:
      labels:
        app: bees
    spec:
      containers:
      - name: nginx
        image: nginx:stable
