apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-06-30T10:14:15Z"
  generation: 1
  name: buffy
  namespace: sunnydale
  resourceVersion: "779"
  uid: e11dafa3-6794-4e29-b741-f7a68fbae982
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: buffy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: buffy
    spec:
      runtimeClassName: sandbox
      containers:
      - command:
        - sh
        - -c
        - while true; do sleep 5; done
        image: busybox:1.33.1
        imagePullPolicy: IfNotPresent
        name: busybox
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-06-30T10:14:39Z"
    lastUpdateTime: "2025-06-30T10:14:39Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-06-30T10:14:15Z"
    lastUpdateTime: "2025-06-30T10:14:39Z"
    message: ReplicaSet "buffy-5c9f5f7d54" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
