apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"comb-monitor","namespace":"hive"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"comb-monitor"}},"template":{"metadata":{"labels":{"app":"comb-monitor"}},"spec":{"containers":[{"command":["sh","-c","while true; do sleep 5; done"],"image":"busybox:stable","name":"busybox"}]}}}}
  creationTimestamp: "2025-06-20T13:43:52Z"
  generation: 1
  name: comb-monitor
  namespace: hive
  resourceVersion: "739"
  uid: 7bb0b02a-13c4-453f-93e7-6103f89a3a55
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: comb-monitor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: comb-monitor
    spec:
      containers:
      - command:
        - sh
        - -c
        - while true; do sleep 5; done
        image: busybox:stable
        imagePullPolicy: IfNotPresent
        name: busybox
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        readinessProbe:
          exec:
            command: ['echo', 'This is a test!']
          initialDelaySeconds: 3
          periodSeconds: 3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-06-20T13:44:08Z"
    lastUpdateTime: "2025-06-20T13:44:08Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-06-20T13:43:52Z"
    lastUpdateTime: "2025-06-20T13:44:08Z"
    message: ReplicaSet "comb-monitor-777f68d85c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
