apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"app-processing","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"processing"}},"template":{"metadata":{"labels":{"app":"processing"}},"spec":{"containers":[{"command":["sh","-c","while true; do cat /data/hivekey.txt \u003e /tempdata/hivekey.txt; cat /tempdata/hivekey.txt; sleep 5; done"],"image":"radial/busyboxplus:curl","name":"busybox","securityContext":{"readOnlyRootFilesystem":true}}]}}}}
  creationTimestamp: "2025-06-19T11:08:41Z"
  generation: 1
  name: app-processing
  namespace: default
  resourceVersion: "665"
  uid: 6e262e82-327e-4ee6-9e03-5757b5e6bcc2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: processing
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: processing
    spec:
      containers:
      - command:
        - sh
        - -c
        - while true; do cat /data/hivekey.txt > /tempdata/hivekey.txt; cat /tempdata/hivekey.txt;
          sleep 5; done
        image: radial/busyboxplus:curl
        imagePullPolicy: IfNotPresent
        name: busybox
        resources: {}
        securityContext:
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: temp
          mountPath: /tempdata
        - name: hostdata
          mountPath: /data          
      volumes:
      - name: temp
        emptyDir: {}
      - name: hostdata
        persistentVolumeClaim:
          claimName: hostdata-pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-06-19T11:08:56Z"
    lastUpdateTime: "2025-06-19T11:08:56Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-06-19T11:08:41Z"
    lastUpdateTime: "2025-06-19T11:08:56Z"
    message: ReplicaSet "app-processing-75bb64f447" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
