apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"hive-mgr","namespace":"hive"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"hive-mgr"}},"template":{"metadata":{"labels":{"app":"hive-mgr"}},"spec":{"containers":[{"command":["sh","-c","echo daily message: $(cat /config/honey.cfg); echo Authenticating with hiveToken $TOKEN; while true; do sleep 5; done"],"image":"busybox:stable","name":"busybox"}]}}}}
  creationTimestamp: "2025-06-20T14:04:27Z"
  generation: 1
  name: hive-mgr
  namespace: hive
  resourceVersion: "762"
  uid: f880ab18-6850-496a-a76f-5b2b3aceaf25
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hive-mgr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hive-mgr
    spec:
      containers:
      - command:
        - sh
        - -c
        - 'echo daily message: $(cat /config/honey.cfg); echo Authenticating with
          hiveToken $TOKEN; while true; do sleep 5; done'
        image: busybox:stable
        imagePullPolicy: IfNotPresent
        name: busybox
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: hive-sec
              key: hiveToken
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: honey-config
          items:
          - key: honey.cfg
            path: honey.cfg      
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2025-06-20T14:04:34Z"
    lastUpdateTime: "2025-06-20T14:04:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-06-20T14:04:27Z"
    lastUpdateTime: "2025-06-20T14:04:34Z"
    message: ReplicaSet "hive-mgr-7b887855fd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
