apiVersion: apps/v1
kind: Deployment
metadata:
  name: lambs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: lambs
  template:
    metadata:
      labels:
        app: lambs
    spec:
      containers:
      - name: nginx
        image: nginx:stable
