apiVersion: apps/v1
kind: Deployment
metadata:
  name: turtles
spec:
  replicas: 3
  selector:
    matchLabels:
      app: turtles
  template:
    metadata:
      labels:
        app: turtles
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-worker9
      containers:
      - name: nginx
        image: nginx:stable
