apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"users-rest","namespace":"hive"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"users-rest"}},"template":{"metadata":{"labels":{"app":"users-rest"}},"spec":{"containers":[{"image":"nginx:1.20.1","name":"nginx","ports":[{"containerPort":80}],"readinessProbe":{"httpGet":{"path":"/","port":8080},"initialDelaySeconds":3,"periodSeconds":3}}]}}}}
  creationTimestamp: "2025-06-20T13:34:11Z"
  generation: 2
  name: users-rest
  namespace: hive
  resourceVersion: "6219"
  uid: 00e8f112-f855-43e8-99a6-c81b95c16a19
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: users-rest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: users-rest
    spec:
      containers:
      - image: nginx:1.20.1
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-06-20T14:39:11Z"
    lastUpdateTime: "2025-06-20T14:39:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-06-20T14:38:59Z"
    lastUpdateTime: "2025-06-20T14:39:11Z"
    message: ReplicaSet "users-rest-7df99f4f77" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
