kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: dDYPhuLIt02WM6WnQcntGzjmM3wlFBL2O7/8CX/6fBw=
      - identity: {}