apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-pod-monitor
  namespace: auth
subjects:
- kind: ServiceAccount
  name: pod-monitor
  namespace: auth
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io