apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: svc-reader-svc-monitor
  namespace: auth
subjects:
- kind: ServiceAccount
  name: svc-monitor
  namespace: auth
roleRef:
  kind: Role
  name: svc-reader
  apiGroup: rbac.authorization.k8s.io