apiVersion: v1
data:
  password: <base64-password> # i.e. aHVudGVyMgo=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"password":"aHVudGVyMgo="},"kind":"Secret","metadata":{"annotations":{},"name":"db-pass","namespace":"users"},"type":"Opaque"}
  creationTimestamp: "2025-06-26T10:03:26Z"
  name: db-pass
  namespace: users
  resourceVersion: "524"
  uid: bd69a73f-d03b-481e-9de9-df883e3d3f1d
type: Opaque