apiVersion: v1
kind: Pod
metadata:
  name: questionablesoft-data
  namespace: questionablesoft
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do echo "Running..."; sleep 5; done']
  runtimeClassName: runsc-sandbox
