apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 518d79716203a8f4a20ec2158ff201265918809cc6477261c62d33655436a505
    cni.projectcalico.org/podIP: 192.168.194.67/32
    cni.projectcalico.org/podIPs: 192.168.194.67/32
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"sunlight","namespace":"default"},"spec":{"containers":[{"image":"gcr.io/kubernetes-e2e-test-images/resource-consumer:1.5","name":"resource-consumer"},{"command":["sh","-c","until curl localhost:8080/ConsumeCPU -d \"millicores=250\u0026durationSec=3600\"; do sleep 5; done \u0026\u0026 while true; do sleep 10; done"],"image":"radial/busyboxplus:curl","name":"busybox-sidecar"}]}}
  creationTimestamp: "2025-06-30T16:13:58Z"
  name: sunlight
  namespace: default
  resourceVersion: "942"
  uid: 8f8927e2-887f-4052-a5a2-107cf4dcb49a
spec:
  containers:
  - image: gcr.io/kubernetes-e2e-test-images/resource-consumer:1.5
    imagePullPolicy: IfNotPresent
    name: resource-consumer
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-qtxxk
      readOnly: true
  - command:
    - sh
    - -c
    - until curl localhost:8080/ConsumeCPU -d "millicores=250&durationSec=3600"; do
      sleep 5; done && while true; do sleep 10; done
    image: radial/busyboxplus:curl
    imagePullPolicy: IfNotPresent
    name: busybox-sidecar
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-qtxxk
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-worker1
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-qtxxk
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-06-30T16:14:26Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-06-30T16:14:56Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-06-30T16:14:56Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-06-30T16:14:25Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://cc2b90a7e48daa01d847ce99862b76bac0b0bc44a6978900ca5ac18f94555591
    image: docker.io/radial/busyboxplus:curl
    imageID: sha256:4776f1f7d1f625c8c5173a969fdc9ae6b62655a2746aba989784bb2b7edbfe9b
    lastState: {}
    name: busybox-sidecar
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-06-30T16:14:55Z"
  - containerID: containerd://048488c2eb5e0323735344513f668941202c238a0207b18b14d69aa8e9f7c0c8
    image: gcr.io/kubernetes-e2e-test-images/resource-consumer:1.5
    imageID: gcr.io/kubernetes-e2e-test-images/resource-consumer@sha256:284fcd047cdec35e1b212919bd878ba5ef72f1da12f49ddc199d219fa8b64f4a
    lastState: {}
    name: resource-consumer
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-06-30T16:14:53Z"
  hostIP: 10.0.1.102
  phase: Running
  podIP: 192.168.194.67
  podIPs:
  - ip: 192.168.194.67
  qosClass: BestEffort
  startTime: "2025-06-30T16:14:26Z"
