apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 8035944f329b6809a08f545c900e82eec2b92e8a6d20eaebbdc81eb83593d1d4
    cni.projectcalico.org/podIP: 192.168.194.68/32
    cni.projectcalico.org/podIPs: 192.168.194.68/32
  creationTimestamp: "2025-06-27T15:09:48Z"
  name: user-svc
  namespace: dev
  resourceVersion: "804"
  uid: 4cb54be7-bb54-4ff9-b766-f3f8302a285c
spec:
  containers:
  - image: nginx:1.19.1
    imagePullPolicy: IfNotPresent
    name: nginx
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false # ---> readOnlyRootFilesystem is false so this is a mutable container
      readOnlyRootFilesystem: false # ---> allowPrivilegeEscalation is false so this is a mutable container
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-txgn9
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-worker1
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-txgn9
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-06-27T15:10:14Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-06-27T15:10:54Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-06-27T15:10:54Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-06-27T15:10:15Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://b593b05927dfd0d120dd6be00caef71242915da63b425fdf4c8ad3a7d9717f85
    image: docker.io/library/nginx:1.19.1
    imageID: docker.io/library/nginx@sha256:36b74457bccb56fbf8b05f79c85569501b721d4db813b684391d63e02287c0b2
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-06-27T15:10:53Z"
  hostIP: 10.0.1.102
  phase: Running
  podIP: 192.168.194.68
  podIPs:
  - ip: 192.168.194.68
  qosClass: BestEffort
  startTime: "2025-06-27T15:10:14Z"
