apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: b25ecd2bc7f76b5298776f00ccf33d7f399dd306bb46bff701a0c52ae7770ded
    cni.projectcalico.org/podIP: 192.168.194.65/32
    cni.projectcalico.org/podIPs: 192.168.194.65/32
  creationTimestamp: "2025-06-27T15:09:47Z"
  name: web-frontend
  namespace: dev
  resourceVersion: "771"
  uid: 62364013-4f46-4b85-8a55-0697136d6c7e
spec:
  containers:
  - image: nginx:1.19.1
    imagePullPolicy: IfNotPresent
    name: nginx
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 0 # ---> running as root cannot be considered immutable
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-2dw8w
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-worker1
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-2dw8w
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-06-27T15:10:14Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-06-27T15:10:45Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-06-27T15:10:45Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-06-27T15:10:15Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://d15ca43bc59f4b0c6db789c7a9fb5d18758756f0a6f215cf81c6f0480bb78254
    image: docker.io/library/nginx:1.19.1
    imageID: docker.io/library/nginx@sha256:36b74457bccb56fbf8b05f79c85569501b721d4db813b684391d63e02287c0b2
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-06-27T15:10:45Z"
  hostIP: 10.0.1.102
  phase: Running
  podIP: 192.168.194.65
  podIPs:
  - ip: 192.168.194.65
  qosClass: BestEffort
  startTime: "2025-06-27T15:10:14Z"
