apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 3c3e57f0c36dc0b055bba2655ca93b9b824d24ca65c0262d26b2c8f119bc8dbe
    cni.projectcalico.org/podIP: 192.168.194.68/32
    cni.projectcalico.org/podIPs: 192.168.194.68/32
  creationTimestamp: "2025-06-30T07:54:06Z"
  name: xander
  namespace: sunnydale
  resourceVersion: "739"
  uid: df293784-764c-4225-981b-7aa1cd3f10d5
spec:
  containers:
  - image: nginx:1.19.1
    imagePullPolicy: IfNotPresent
    name: nginx
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false # mutable
      readOnlyRootFilesystem: false # mutable
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-kknth
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-worker1
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-kknth
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-06-30T07:54:06Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-06-30T07:54:13Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-06-30T07:54:13Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-06-30T07:54:06Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://149f733a7eb764a98f5fbdce9b6b1bdfe6746ff6e1b6f044af92cbbd82df4293
    image: docker.io/library/nginx:1.19.1
    imageID: docker.io/library/nginx@sha256:36b74457bccb56fbf8b05f79c85569501b721d4db813b684391d63e02287c0b2
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-06-30T07:54:12Z"
  hostIP: 10.0.1.102
  phase: Running
  podIP: 192.168.194.68
  podIPs:
  - ip: 192.168.194.68
  qosClass: BestEffort
  startTime: "2025-06-30T07:54:06Z"
